apiVersion: v1
kind: ReplicationController
metadata:
  name: app-rc
  labels:
    app: app1
    type: front-end
spec:
  template:
    metadata:
     name: pod2
     labels:
      app: app1
      type: front-end
    spec:
        containers:
            - name: nginx-container
              image: nginx

  replicas: 3                
