apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: app1-replicaset
  labels:
    app: app1
    type: front-end
spec:
  template:
    metadata:
     name: pod2
     labels:
      app: app1
      type: front-end
    spec:
        containers:
            - name: nginx-container
              image: nginx

  replicas: 3
  selector:
    matchLabels:
     type: front-end
